apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: donghk77/literature:latest
          ports:
            - containerPort: 8000
          env:
            - name: DJANGO_SETTINGS_MODULE
              value: config.settings.prod
            - name: EMAIL_HOST_USER
              valueFrom:
                secretKeyRef:
                  name: email-secret
                  key: EMAIL_HOST_USER
            - name: EMAIL_HOST_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: email-secret
                  key: EMAIL_HOST_PASSWORD
          command: ["/bin/sh", "-c"]
          args:
            - |
              python manage.py makemigrations --noinput &&
              python manage.py migrate &&
              python manage.py runserver 0.0.0.0:8000