apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "grafana.fullname" . }}-datasources
  labels:
    app: {{ include "grafana.name" . }}
data:
  datasources.yaml: |-
{{ toYaml .Values.datasources.datasources.yaml | indent 4 }}
