apiVersion: v1
kind: Service
metadata:
  name: {{ include "grafana.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: 3000
      nodePort: {{ .Values.service.nodePort }}
  selector:
    app: {{ include "grafana.name" . }}
