name: Django CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up SSH keys
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.AWS_LS_SSH_KEY }}

      - name: Deploy to AWS Lightsail
        run: |
          ssh -o StrictHostKeyChecking=no -i /tmp/id_rsa ubuntu@${{ secrets.AWS_LS_IP }} << 'EOF'

            # 루트 권한을 얻기 위해 sudo -i 사용
            sudo -i

            # Django 프로젝트 디렉토리로 이동
            cd /home/Literature

            # 최신 코드로 업데이트
            git pull origin main

            # 가상 환경 생성 및 활성화 (존재하지 않으면)
            if [ ! -d "venv" ]; then
              python3 -m venv venv
            fi
            source venv/bin/activate

            # 필요한 패키지 설치
            pip install -r requirements.txt

            # 마이그레이션 파일 생성
            python manage.py makemigrations

            # 데이터베이스 마이그레이션
            python manage.py migrate

            # Django 애플리케이션 재시작 (supervisor 또는 systemd를 사용하여)
            sudo systemctl restart django-app
          EOF
